In [1]:
import pandas as pd
import numpy as np

In [2]:
Sellers_table=pd.read_csv(r"C:\Users\vinot\OneDrive\Desktop\Seller Data\2026-01-05.csv")

In [3]:
Sellers_table.head()

,SKU,Marketplace,Seller_name,region,adv_price,Screenshot,live_link
0,6N4F1AA,eBay,Jishnu Enterprises India,IND,18200.0000,NaN,NaN
1,7WN44D,Amazon,TREASURE SHARK,USA,52.9200,NaN,NaN
2,6X4B5PA,Flipkart,HUMARABAZAR INDIA,CAN,685.7600,NaN,NaN
3,CF360X,eBay,More HM Galaxy Sapphire Noida,UK,178.5342,NaN,NaN
4,CF502A,Amazon,OFFICIAL KEY STORE [ EMAIL DELIVERY ONLY ],USA,87.3600,NaN,NaN

In [4]:
Sellers_table.shape

(9860, 7)

In [5]:
Sellers_table.isna().sum()

SKU               0
Marketplace       0
Seller_name       0
region            0
adv_price         0
Screenshot     9860
live_link      9860
dtype: int64

In [6]:
Sellers_table.drop_duplicates()

,SKU,Marketplace,Seller_name,region,adv_price,Screenshot,live_link
0,6N4F1AA,eBay,Jishnu Enterprises India,IND,18200.0000,NaN,NaN
1,7WN44D,Amazon,TREASURE SHARK,USA,52.9200,NaN,NaN
2,6X4B5PA,Flipkart,HUMARABAZAR INDIA,CAN,685.7600,NaN,NaN
3,CF360X,eBay,More HM Galaxy Sapphire Noida,UK,178.5342,NaN,NaN
4,CF502A,Amazon,OFFICIAL KEY STORE [ EMAIL DELIVERY ONLY ],USA,87.3600,NaN,NaN
...,...,...,...,...,...,...,...
9855,W1104A,eBay,UTOPIA ENTERPRISES,UAE,352.4400,NaN,NaN
9856,3ED45A,eBay,Techsaaz Solutions LLP,UK,63.5440,NaN,NaN
9857,2Y9H2A,Snapdeal,LOURYN KOULYN,UAE,6739.4800,NaN,NaN
9858,81H48PA,Snapdeal,Lowfe® Online Store (100% CUSTOMER SATISFACTION),CAN,1241.7600,NaN,NaN
9859,W2043A,Flipkart,Lakulish Enterprise®,USA,146.1600,NaN,NaN

In [7]:
Sellers_table.drop(['Screenshot','live_link'],axis=1,inplace=True)

In [8]:
Sellers_table

,SKU,Marketplace,Seller_name,region,adv_price
0,6N4F1AA,eBay,Jishnu Enterprises India,IND,18200.0000
1,7WN44D,Amazon,TREASURE SHARK,USA,52.9200
2,6X4B5PA,Flipkart,HUMARABAZAR INDIA,CAN,685.7600
3,CF360X,eBay,More HM Galaxy Sapphire Noida,UK,178.5342
4,CF502A,Amazon,OFFICIAL KEY STORE [ EMAIL DELIVERY ONLY ],USA,87.3600
...,...,...,...,...,...
9855,W1104A,eBay,UTOPIA ENTERPRISES,UAE,352.4400
9856,3ED45A,eBay,Techsaaz Solutions LLP,UK,63.5440
9857,2Y9H2A,Snapdeal,LOURYN KOULYN,UAE,6739.4800
9858,81H48PA,Snapdeal,Lowfe® Online Store (100% CUSTOMER SATISFACTION),CAN,1241.7600
9859,W2043A,Flipkart,Lakulish Enterprise®,USA,146.1600

In [9]:
Sellers_table['region'].unique()

array(['IND', 'USA', 'CAN', 'UK', 'UAE'], dtype=object)

# ===========================================================================================

In [10]:
import mysql.connector
import pandas as pd

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Root@123",
    database="mappriceetl")

In [11]:
df = pd.read_sql("SELECT*FROM price_list",conn)
df

C:\Users\vinot\AppData\Local\Temp\ipykernel_23528\2473678360.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT*FROM price_list",conn)

                     PL      SKU     MAP         LPP
0      DELL0X_PC_Laptop  0X749QB  106684   98362.648
1     DELL75_PC_Monitor  75X62BB   35611   33616.784
2        DELLDF_SUP_TON   DF627B   29914   29225.978
3            HP4Z_PH_LJ   4ZB96A   39258   36706.230
4      DELL0R_PC_Laptop  0R0N0QB  139670  128775.740
...                 ...      ...     ...         ...
1553     DELL4K_SUP_INK  4KB93BB    3565    3440.225
1554     DELLX2_SUP_TON   X2231B    6716    6561.532
1555       HPB3_SUP_INK   B3P21A    6868    6421.580
1556  DELL78_PC_Desktop  78X20QB   47937   46834.449
1557       HPCF_SUP_TON   CF364A   28243   25672.887

[1558 rows x 4 columns]

In [12]:
df2 = pd.read_sql("SELECT*FROM pl_table",conn)
df2

C:\Users\vinot\AppData\Local\Temp\ipykernel_23528\2643837242.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql("SELECT*FROM pl_table",conn)

                     PL      SKU SUB_CATEGORY
0      DELL0X_PC_Laptop  0X749QB       Laptop
1     DELL75_PC_Monitor  75X62BB      Monitor
2        DELLDF_SUP_TON   DF627B        Toner
3            HP4Z_PH_LJ   4ZB96A     Laserjet
4      DELL0R_PC_Laptop  0R0N0QB       Laptop
...                 ...      ...          ...
1545     DELL4K_SUP_INK  4KB93BB          Ink
1546     DELLX2_SUP_TON   X2231B        Toner
1547       HPB3_SUP_INK   B3P21A          Ink
1548  DELL78_PC_Desktop  78X20QB      Desktop
1549       HPCF_SUP_TON   CF364A        Toner

[1550 rows x 3 columns]

In [13]:
merge_df = pd.merge(df,df2,on=["PL", "SKU"],how="inner")
merge_df.head()

                  PL      SKU     MAP         LPP SUB_CATEGORY
0   DELL0X_PC_Laptop  0X749QB  106684   98362.648       Laptop
1  DELL75_PC_Monitor  75X62BB   35611   33616.784      Monitor
2     DELLDF_SUP_TON   DF627B   29914   29225.978        Toner
3         HP4Z_PH_LJ   4ZB96A   39258   36706.230     Laserjet
4   DELL0R_PC_Laptop  0R0N0QB  139670  128775.740       Laptop

In [14]:
merge_df.isna().sum()

PL              0
SKU             0
MAP             0
LPP             0
SUB_CATEGORY    0
dtype: int64

In [15]:
merge_df.shape

(1558, 5)

# -------------------------------------------------------------------------------------

In [16]:
merge_df2 = pd.merge(Sellers_table,merge_df,on="SKU",how="inner")
merge_df2

,SKU,Marketplace,Seller_name,region,adv_price,PL,MAP,LPP,SUB_CATEGORY
0,6N4F1AA,eBay,Jishnu Enterprises India,IND,18200.0000,HP6N_PC_Monitor,15966,15774.408,Monitor
1,7WN44D,Amazon,TREASURE SHARK,USA,52.9200,HP7W_PH_IJ,3905,3858.140,Inkjet
2,6X4B5PA,Flipkart,HUMARABAZAR INDIA,CAN,685.7600,HP6X_PC_Desktop,40816,37101.744,Desktop
3,CF360X,eBay,More HM Galaxy Sapphire Noida,UK,178.5342,HPCF_SUP_TON,22131,20117.079,Toner
4,CF502A,Amazon,OFFICIAL KEY STORE [ EMAIL DELIVERY ONLY ],USA,87.3600,HPCF_SUP_TON,8112,7373.808,Toner
...,...,...,...,...,...,...,...,...,...
9838,W1104A,eBay,UTOPIA ENTERPRISES,UAE,352.4400,HPW1_SUP_TON,7152,6501.168,Toner
9839,3ED45A,eBay,Techsaaz Solutions LLP,UK,63.5440,HP3E_SUP_INK,5983,5594.105,Ink
9840,2Y9H2A,Snapdeal,LOURYN KOULYN,UAE,6739.4800,HP2Y_PH_IJ,251105,248091.740,Inkjet
9841,81H48PA,Snapdeal,Lowfe® Online Store (100% CUSTOMER SATISFACTION),CAN,1241.7600,HP81_PC_Laptop,73919,71405.754,Laptop
9842,W2043A,Flipkart,Lakulish Enterprise®,USA,146.1600,HPW2_SUP_TON,11486,10440.774,Toner

In [17]:
merge_df2.drop_duplicates(inplace=True)

In [18]:
merge_df2

,SKU,Marketplace,Seller_name,region,adv_price,PL,MAP,LPP,SUB_CATEGORY
0,6N4F1AA,eBay,Jishnu Enterprises India,IND,18200.0000,HP6N_PC_Monitor,15966,15774.408,Monitor
1,7WN44D,Amazon,TREASURE SHARK,USA,52.9200,HP7W_PH_IJ,3905,3858.140,Inkjet
2,6X4B5PA,Flipkart,HUMARABAZAR INDIA,CAN,685.7600,HP6X_PC_Desktop,40816,37101.744,Desktop
3,CF360X,eBay,More HM Galaxy Sapphire Noida,UK,178.5342,HPCF_SUP_TON,22131,20117.079,Toner
4,CF502A,Amazon,OFFICIAL KEY STORE [ EMAIL DELIVERY ONLY ],USA,87.3600,HPCF_SUP_TON,8112,7373.808,Toner
...,...,...,...,...,...,...,...,...,...
9838,W1104A,eBay,UTOPIA ENTERPRISES,UAE,352.4400,HPW1_SUP_TON,7152,6501.168,Toner
9839,3ED45A,eBay,Techsaaz Solutions LLP,UK,63.5440,HP3E_SUP_INK,5983,5594.105,Ink
9840,2Y9H2A,Snapdeal,LOURYN KOULYN,UAE,6739.4800,HP2Y_PH_IJ,251105,248091.740,Inkjet
9841,81H48PA,Snapdeal,Lowfe® Online Store (100% CUSTOMER SATISFACTION),CAN,1241.7600,HP81_PC_Laptop,73919,71405.754,Laptop
9842,W2043A,Flipkart,Lakulish Enterprise®,USA,146.1600,HPW2_SUP_TON,11486,10440.774,Toner

In [19]:
merge_df2['adv_price'] = pd.to_numeric(merge_df2['adv_price'],errors='coerce')

conversion_rates = {
    'IND':1,
    'USA':91.17,
    'UK':91.07*1.27,
    'CAN':91.07*0.74,
    'UAE':91.07*0.27 }

merge_df2['adv_price_inr'] = merge_df2.apply(
    lambda row: row['adv_price']*conversion_rates.get(row['region'],1),axis=1)
merge_df2.head()

,SKU,Marketplace,Seller_name,region,adv_price,PL,MAP,LPP,SUB_CATEGORY,adv_price_inr
0,6N4F1AA,eBay,Jishnu Enterprises India,IND,18200.0000,HP6N_PC_Monitor,15966,15774.408,Monitor,18200.000000
1,7WN44D,Amazon,TREASURE SHARK,USA,52.9200,HP7W_PH_IJ,3905,3858.140,Inkjet,4824.716400
2,6X4B5PA,Flipkart,HUMARABAZAR INDIA,CAN,685.7600,HP6X_PC_Desktop,40816,37101.744,Desktop,46214.600768
3,CF360X,eBay,More HM Galaxy Sapphire Noida,UK,178.5342,HPCF_SUP_TON,22131,20117.079,Toner,20649.069184
4,CF502A,Amazon,OFFICIAL KEY STORE [ EMAIL DELIVERY ONLY ],USA,87.3600,HPCF_SUP_TON,8112,7373.808,Toner,7964.611200

In [20]:
merge_df2.isna().sum()

SKU              0
Marketplace      0
Seller_name      0
region           0
adv_price        0
PL               0
MAP              0
LPP              0
SUB_CATEGORY     0
adv_price_inr    0
dtype: int64

In [21]:
merge_df2.shape

(9843, 10)

In [22]:
violation = merge_df2[merge_df2['adv_price_inr'] < merge_df2['LPP']]
print("Total Violations:",violation['SKU'].count())

Total Violations: 748

In [23]:
violation['SKU'].nunique()

520

In [24]:
violation.isna().sum()

SKU              0
Marketplace      0
Seller_name      0
region           0
adv_price        0
PL               0
MAP              0
LPP              0
SUB_CATEGORY     0
adv_price_inr    0
dtype: int64

In [25]:
import os
import re

folder_name = "warning_letters"
os.makedirs(folder_name, exist_ok=True)

for index, row in violation.iterrows():

    # Clean seller name for file safety
    seller_clean = re.sub(r'[^a-zA-Z0-9]', '_', str(row['Seller_name']))
    
    file_name = f"{row['SKU']}_{seller_clean}.txt"
    file_path = os.path.join(folder_name, file_name)

    letter = f"""
Date: 2026-02-25

Subject: Price Violation Warning – LPP Policy

Dear {row['Seller_name']},

We have identified a pricing violation for the following product:

SKU              : {row['SKU']}
Marketplace      : {row['Marketplace']}
Region           : {row['region']}
Advertised Price : {row['adv_price_inr']}
LPP Price        : {row['LPP']}
Category         : {row['SUB_CATEGORY']}

Your advertised price is lower than the allowed LPP price.
This is a violation of our pricing policy.

Please correct the advertised price within 24 hours of receiving this notice.

Failure to comply within 24 hours may result in listening suspension or further action as per policy.

If you believe this notice was issued in error, please contact us immediately.

Regards,
MAP Compliance Team
"""

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(letter)

print("All warning letters generated successfully!")

All warning letters generated successfully!

# -----------------------------------------------------------------------------